export const START_CREATE_DASHBOARD = 'START_CREATE_DASHBOARD';
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS';
export const CREATE_DASHBOARD_FAILED = 'CREATE_DASHBOARD_FAILED';

export const START_UPDATE_DASHBOARD = 'START_UPDATE_DASHBOARD';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const UPDATE_DASHBOARD_FAILED = 'UPDATE_DASHBOARD_FAILED';

export const START_CREATE_TRELLO_COLUMN = 'START_CREATE_TRELLO_COLUMN';
export const CREATE_TRELLO_COLUMN_SUCCESS = 'CREATE_TRELLO_COLUMN_SUCCESS';
export const CREATE_TRELLO_COLUMN_FAILED = 'CREATE_TRELLO_COLUMN_FAILED';

export const START_UPDATE_TRELLO_COLUMNS = 'START_UPDATE_TRELLO_COLUMNS';
export const UPDATE_TRELLO_COLUMNS_SUCCESS = 'UPDATE_TRELLO_COLUMNS_SUCCESS';
export const UPDATE_TRELLO_COLUMNS_FAILED = 'UPDATE_TRELLO_COLUMNS_FAILED';

export const START_CREATE_TRELLO_CARD = 'START_CREATE_TRELLO_CARD';
export const CREATE_TRELLO_CARD_SUCCESS = 'CREATE_TRELLO_CARD_SUCCESS';
export const CREATE_TRELLO_CARD_FAILED = 'CREATE_TRELLO_CARD_FAILED';

export const START_UPDATE_TRELLO_CARD = 'START_UPDATE_TRELLO_CARD';
export const UPDATE_TRELLO_CARD_SUCCESS = 'UPDATE_TRELLO_CARD_SUCCESS';
export const UPDATE_TRELLO_CARD_FAILED = 'UPDATE_TRELLO_CARD_FAILED';
