export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILES';

export const START_LOGOUT = 'START_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILES';

export const START_SIGNUP = 'START_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILES';

// DASHBOARD
export const START_FETCH_DASHBOARDS = 'START_FETCH_DASHBOARDS';
export const FETCH_DASHBOARDS_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
export const FETCH_DASHBOARDS_FAILED = 'FETCH_DASHBOARDS_FAILED';

export const START_CREATE_DASHBOARD = 'START_CREATE_DASHBOARD';
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS';
export const CREATE_DASHBOARD_FAILED = 'CREATE_DASHBOARD_FAILED';

export const START_UPDATE_DASHBOARD = 'START_UPDATE_DASHBOARD';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const UPDATE_DASHBOARD_FAILED = 'UPDATE_DASHBOARD_FAILED';

export const START_DELETE_DASHBOARD = 'START_DELETE_DASHBOARD';
export const DELETE_DASHBOARD_SUCCESS = 'DELETE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_FAILED = 'DELETE_DASHBOARD_FAILED';

export const SUBSCRIBE_DASHBOARD = 'SUBSCRIBE_DASHBOARD';
export const UNSUBSCRIBE_DASHBOARD = 'UNSUBSCRIBE_DASHBOARD';
export const SET_DASHBOARD = 'SET_DASHBOARD';

// TRELLO_COLUMN
export const START_CREATE_TRELLO_COLUMN = 'START_CREATE_TRELLO_COLUMN';
export const CREATE_TRELLO_COLUMN_SUCCESS = 'CREATE_TRELLO_COLUMN_SUCCESS';
export const CREATE_TRELLO_COLUMN_FAILED = 'CREATE_TRELLO_COLUMN_FAILED';

export const START_UPDATE_TRELLO_COLUMNS = 'START_UPDATE_TRELLO_COLUMNS';
export const UPDATE_TRELLO_COLUMNS_SUCCESS = 'UPDATE_TRELLO_COLUMNS_SUCCESS';
export const UPDATE_TRELLO_COLUMNS_FAILED = 'UPDATE_TRELLO_COLUMNS_FAILED';

export const START_DELETE_TRELLO_COLUMN = 'START_DELETE_TRELLO_COLUMN';
export const DELETE_TRELLO_COLUMNS_SUCCES = 'DELETE_TRELLO_COLUMNS_SUCCES';
export const DELETE_TRELLO_COLUMNS_FAILE = 'DELETE_TRELLO_COLUMNS_FAILE';

export const SUBSCRIBE_TRELLO_COLUMNS = 'SUBSCRIBE_TRELLO_COLUMNS';
export const UNSUBSCRIBE_TRELLO_COLUMNS = 'UNSUBSCRIBE_TRELLO_COLUMNS';
export const SET_TRELLO_COLUMN = 'SET_TRELLO_COLUMN';

// TRELLO_CARD
export const START_CREATE_TRELLO_CARD = 'START_CREATE_TRELLO_CARD';
export const CREATE_TRELLO_CARD_SUCCESS = 'CREATE_TRELLO_CARD_SUCCESS';
export const CREATE_TRELLO_CARD_FAILED = 'CREATE_TRELLO_CARD_FAILED';

export const START_UPDATE_TRELLO_CARDS = 'START_UPDATE_TRELLO_CARDS';
export const UPDATE_TRELLO_CARDS_SUCCESS = 'UPDATE_TRELLO_CARDS_SUCCESS';
export const UPDATE_TRELLO_CARDS_FAILED = 'UPDATE_TRELLO_CARDS_FAILED';

export const START_DELETE_TRELLO_CARD = 'START_DELETE_TRELLO_CARD';
export const DELETE_TRELLO_CARD_SUCCESS = 'DELETE_TRELLO_CARD_SUCCESS';
export const DELETE_TRELLO_CARD_FAILED = 'DELETE_TRELLO_CARD_FAILED';

export const SUBSCRIBE_TRELLO_CARDS = 'SUBSCRIBE_TRELLO_CARDS';
export const UNSUBSCRIBE_TRELLO_CARDS = 'UNSUBSCRIBE_TRELLO_CARDS';
export const SET_TRELLO_CARD = 'SET_TRELLO_CARD';

export const SET_USER = 'SET_USER';
